Sprint 07
bkljn4g/MovieQuiz-ios pull request #7
Opened 2023-03-17 19:02 UTC by bkljn4g

Версия для ревью

2023-03-18 09:59 UTC, protos17 requested changes

2023-03-18 09:59 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Рекомендую использовать hidesWhenStopped вместо ручного управления показом

2023-03-18 09:59 UTC, protos17 commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Рекомендую использовать уникальные значения, потому что array[safe: 0] и array[safe: 1] дадут одинаковый результат

2023-03-18 09:59 UTC, protos17 commented on MovieQuizTests/ArrayTests.swift
> +class ArrayTests: XCTestCase {
Для тестовых классов рекомендую тоже указать как final

2023-03-18 09:59 UTC, protos17 commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Рекомендую использовать уникальные значения

2023-03-18 09:59 UTC, protos17 commented on MovieQuizTests/MoviesLoaderTests.swift
> +class MoviesLoaderTests: XCTestCase {
Рекомендую пометить как final

2023-03-18 09:59 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Рекомендую убрать, потому что ни на что не влияет, кроме задержки начала теста

2023-03-18 09:59 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Рекомендую убрать

2023-03-18 09:59 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(2)
Рекомендую убрать

2023-03-18 09:59 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(2)
Рекомендую убрать

2023-03-18 10:39 UTC, bkljn4g commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Ок! Поменяла

2023-03-18 10:40 UTC, bkljn4g commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Исправила

2023-03-18 10:41 UTC, bkljn4g commented on MovieQuizTests/ArrayTests.swift
> +class ArrayTests: XCTestCase {
Готово

2023-03-18 10:41 UTC, bkljn4g commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Поменяла

2023-03-18 10:42 UTC, bkljn4g commented on MovieQuizTests/MoviesLoaderTests.swift
> +class MoviesLoaderTests: XCTestCase {
Добавила

2023-03-18 10:43 UTC, bkljn4g commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Убрала

2023-03-18 10:43 UTC, bkljn4g commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Готово

2023-03-18 10:44 UTC, bkljn4g commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(2)
Готово

2023-03-18 10:44 UTC, bkljn4g commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(2)
Готово

2023-03-18 11:06 UTC, bkljn4g commented
Внесла все исправления. 
UI-тесты проходят успешно

2023-03-19 11:15 UTC, protos17 approved these changes

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            //viewController.showLoadingIndicator()
Закомментированный код рекомендую удалить

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
Лишние отступы по проекту рекомендую удалить, оставляй максимум 1 отступ

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +                //viewController?.showLoadingIndicator()
Стоит удалить

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        //showLoadingIndicator() // заменила на hidesWhenStopped
Отлично, молодец! Стоит удалить строчку, если не используется

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Стоит удалить закомментированный код

2023-03-19 11:15 UTC, protos17 commented on MovieQuiz/Services/MovieQuizViewControllerProtocol.swift
> +    //func showLoadingIndicator() - меняю на hidesWhenStopped
Не забудь удалить

2023-03-19 11:15 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        //sleep(3)
Можно удалить

2023-03-19 11:46 UTC, bkljn4g commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            //viewController.showLoadingIndicator()
Готово

2023-03-19 11:50 UTC, bkljn4g commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
Готово

2023-03-19 11:50 UTC, bkljn4g commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +                //viewController?.showLoadingIndicator()
Удалила

2023-03-19 11:51 UTC, bkljn4g commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        //showLoadingIndicator() // заменила на hidesWhenStopped
Спасибо, удалила) Оставляла как напоминание себе что на что поменяла

2023-03-19 11:51 UTC, bkljn4g commented on MovieQuiz/Services/MovieQuizViewControllerProtocol.swift
> +    //func showLoadingIndicator() - меняю на hidesWhenStopped
Почистила код от лишних комментариев =)

2023-03-19 11:52 UTC, bkljn4g commented on MovieQuizUITests/MovieQuizUITests.swift
> +        //sleep(3)
Сделано

2023-03-19 11:54 UTC, merged